title: easy-deposit-agreement-generator
description: >-
  JSON-based  service to generate Deposit Agreements.
baseurl: "/easy-deposit-agreement-generator"
github_username: DANS-KNAW

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
